### ISSUE TITLE
Sonderzeichen verhalten sich sonderbar in der Suchleiste

### ISSUE THREAD

**Issue by f0rkster** [Avartos/Webaufbau#67]

**Comment by LittleBigPlaye** [comment]
encodeURIComponent im Frontend und decodeURIComponent im Backend eingefügt. Sonderzeichen funktionieren jetzt.
Implementiert, dass die Suchleiste den Suchparameter bei Neuladen der Seite standardmäßig anzeigt
Ticket kann geschlossen werden.
